/**
 * generate.js — renders policy.yaml, .husky/pre-commit, .husky/pre-push,
 * and .github/workflows/security.yml from the CORE (language-agnostic)
 * rules plus the extra rules contributed by each selected stack profile.
 */
const { STACKS } = require("./stacks");

// Core rules apply regardless of language — they operate on shell/git/db
// semantics, not on the project's source language.
const CORE_PROTECTED_PATHS = [
  ".env", ".env.*", "**/*credentials*", "**/*secret*",
  "~/.ssh/**", "~/.aws/**", "~/.config/gcloud/**", "**/*.pem", "**/*.key",
];

const CORE_BLOCKED_COMMANDS = [
  { pattern: "\\bgit\\s+push\\s+(--force|-f|--force-with-lease)\\b", action: "deny", reason: "Force push blocked." },
  { pattern: "\\bgit\\s+push\\b", action: "ask", reason: "Pushing changes requires explicit human approval." },
  { pattern: "\\bgit\\s+(reset\\s+--hard|clean\\s+-f|branch\\s+-D)\\b", action: "deny", reason: "Destructive Git operation blocked." },
  { pattern: "\\brm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*|--recursive.*--force|--force.*--recursive)\\b", action: "deny", reason: "Recursive forced deletion blocked." },
  { pattern: "\\b(git\\s+commit\\s+.*--no-verify|git\\s+push\\s+.*--no-verify)\\b", action: "deny", reason: "Hook bypass is not permitted." },
  { pattern: "\\b(DROP\\s+DATABASE|DROP\\s+TABLE|TRUNCATE)\\b", action: "deny", reason: "Destructive database operation blocked." },
  { pattern: "\\bDELETE\\s+FROM\\b(?!.*\\bWHERE\\b)", action: "deny", reason: "DELETE without WHERE clause blocked." },
  { pattern: "\\bDELETE\\s+FROM\\b", action: "ask", reason: "Potentially destructive database operation requires approval." },
  { pattern: "\\bcurl\\b.*\\|\\s*(sh|bash|zsh)\\b", action: "deny", reason: "curl-pipe-shell execution blocked." },
  { pattern: "\\bdocker\\s+push\\b", action: "ask", reason: "Pushing a container image requires approval." },
  { pattern: "\\b(aws|gcloud|az)\\s+.*(delete|terminate|destroy)\\b", action: "ask", reason: "Cloud-provider destructive action requires approval." },
];

function yamlStr(s) {
  return JSON.stringify(s); // valid YAML flow scalar, handles escaping
}

function renderBlockedCommand(rule) {
  return `  - pattern: '${rule.pattern.replace(/'/g, "''")}'\n    action: ${rule.action}\n    reason: ${yamlStr(rule.reason)}\n`;
}

function renderCheck(check) {
  return `  - name: ${check.name}\n    command: ${yamlStr(check.command)}\n`;
}

function buildPolicyYaml(selectedStackKeys) {
  const stacks = selectedStackKeys.map((k) => STACKS[k]).filter(Boolean);

  const blockedCommands = [...CORE_BLOCKED_COMMANDS];
  stacks.forEach((s) => blockedCommands.push(...(s.extraBlocked || [])));

  const checks = [];
  stacks.forEach((s) => {
    s.checks.forEach((c) => {
      if (!checks.find((existing) => existing.name === c.name && existing.command === c.command)) {
        checks.push(c);
      }
    });
  });

  const allExtensions = [...new Set(stacks.flatMap((s) => s.changedExtensions))];
  const checkNames = checks.map((c) => c.name);

  let out = "version: 1\n\n";
  out += `# Stacks detected/selected at install time: ${stacks.map((s) => s.label).join(", ") || "(none — generic project)"}\n`;
  out += "# This file is generated by install.js. Edit freely — re-running the\n";
  out += "# installer will NOT overwrite it if it already exists (writes .new instead).\n\n";

  out += "protected_paths:\n" + CORE_PROTECTED_PATHS.map((p) => `  - "${p}"\n`).join("");
  out += "\nblocked_commands:\n" + blockedCommands.map(renderBlockedCommand).join("\n");

  out += "\nsensitive_tools:\n  - write_file\n  - edit_file\n  - run_command\n  - browser\n  - network_request\n";
  out += "\napproval_required:\n  - production\n  - deployment\n  - database_migration\n  - secret_rotation\n  - git_push\n";

  out += "\nrequired_checks:\n";
  out += checks.length
    ? checks.map(renderCheck).join("")
    : "  # No stack detected — add your test/lint/typecheck commands here manually.\n";

  out += "\ncompletion_rules:\n";
  if (allExtensions.length) {
    out += `  - changed_extensions: [${allExtensions.map((e) => `"${e}"`).join(", ")}]\n    require: [${checkNames.join(", ")}]\n`;
  }
  out += `  - changed_files:\n      - "Dockerfile"\n      - ".github/workflows/**"\n    require: []\n`;

  return out;
}

function renderShellChecks(stacks, indent = "") {
  const lines = [];
  stacks.forEach((s) => {
    s.checks.forEach((c) => {
      lines.push(`${indent}echo "[${c.name}] ${s.label}"`);
      lines.push(`${indent}${c.command}`);
    });
  });
  return lines.length ? lines.join("\n") : `${indent}echo "No stack-specific checks configured — edit .husky/pre-push manually."`;
}

function buildPreCommit(selectedStackKeys) {
  return `#!/usr/bin/env bash
# Fast local checks. Assume this CAN be bypassed with --no-verify — it's a
# convenience layer, not the enforcement layer (that's CI + branch protection).
set -euo pipefail

echo "[pre-commit] Checking for secrets..."
if command -v gitleaks >/dev/null 2>&1; then
  gitleaks protect --staged --redact
else
  echo "[pre-commit] gitleaks not installed, skipping secret scan (install: https://github.com/gitleaks/gitleaks)"
fi

echo "[pre-commit] Done."
`;
}

function buildPrePush(selectedStackKeys) {
  const stacks = selectedStackKeys.map((k) => STACKS[k]).filter(Boolean);
  return `#!/usr/bin/env bash
# Slower checks: full test suite per detected stack, then the completion gate.
set -euo pipefail

${renderShellChecks(stacks)}

echo "[pre-push] Completion gate..."
node .agent-security/final_check.js
`;
}

function buildCiWorkflow(selectedStackKeys) {
  const stacks = selectedStackKeys.map((k) => STACKS[k]).filter(Boolean);
  const setupSteps = stacks
    .map(
      (s) => `      - uses: ${s.ci.setupAction}
        with:
          ${s.ci.withBlock}
      - name: Install deps (${s.label})
        run: ${s.ci.install}`
    )
    .join("\n\n");

  const checkSteps = stacks
    .flatMap((s) => s.checks.map((c) => `      - name: ${c.name} (${s.label})\n        run: ${c.command}`))
    .join("\n\n");

  return `# Place at .github/workflows/security.yml
name: security-gate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  guardrails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # The policy engine runs on Node and vendors its only dependency, so
      # there is nothing to install before testing it.
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Test policy engine
        run: node .agent-security/test_policy_engine.js

${setupSteps || "      # No stack detected at install time — add your language's setup step here."}

${checkSteps || "      # No stack-specific checks configured."}

      - name: Secret scan
        uses: gitleaks/gitleaks-action@v2

      # Add SAST / dependency scanning here (Semgrep, npm audit, composer audit, etc).
`;
}

function buildGitlabCiYaml(selectedStackKeys) {
  const stacks = selectedStackKeys.map((k) => ({ key: k, ...STACKS[k] })).filter((s) => s.label);

  const stackJobs = stacks
    .map((s) => {
      if (!s.gitlabCi) return "";
      const scriptLines = [s.gitlabCi.install, ...s.checks.map((c) => c.command)];
      return `${s.key}-checks:
  stage: test
  image: ${s.gitlabCi.image}
  script:
${scriptLines.map((l) => `    - ${yamlStr(l)}`).join("\n")}
`;
    })
    .filter(Boolean)
    .join("\n");

  return `# Place at .gitlab-ci.yml (repo root)
stages:
  - test

policy-engine-test:
  stage: test
  # The policy engine runs on Node and vendors its only dependency, so this job
  # needs nothing beyond a Node image.
  image: node:20
  script:
    - node .agent-security/test_policy_engine.js

${stackJobs || "# No stack detected at install time — add your language's job here.\n"}
secret-scan:
  stage: test
  image: zricethezav/gitleaks:latest
  script:
    - gitleaks detect --source . --no-git -v

# Add SAST / dependency scanning here (Semgrep, npm audit, composer audit, etc).
`;
}

// ── chaining a project's pre-existing git hooks ───────────────────────────
//
// Setting core.hooksPath to .husky/ does not make .husky "win" over the old
// hooks directory — it makes git stop looking at the old one entirely. So a
// project that had its own hooks loses them, including hook types we do not
// generate at all (commit-msg, post-merge, …), which have no replacement.
//
// The fix is to invoke the original hook first and keep its exit code. See
// buildChainShim / buildPassthroughHook below and detectPreviousHooks() in
// install.js.

/**
 * Hooks git feeds data to on stdin. Only matters when the shim is PREPENDED to
 * a hook of ours: whoever reads stdin first consumes it, so it has to be
 * captured and replayed. A pure passthrough needs none of that, because nothing
 * runs after the chained hook.
 */
const HOOKS_WITH_STDIN = ["pre-push", "post-rewrite", "reference-transaction"];

/**
 * Where a shim finds the original hook.
 *
 *   { kind: "literal", dir: ".githooks" }
 *     The project had core.hooksPath set. That value is committed config, so it
 *     means the same thing on every machine — reference it verbatim.
 *
 *   { kind: "gitdir" }
 *     The hooks were in git's own directory, which is NOT committed. Resolve it
 *     at run time so each developer chains their own local hooks.
 *
 *     It has to be --git-common-dir, not --git-path hooks: the latter respects
 *     core.hooksPath, which by then points at .husky/, so the shim would call
 *     itself forever. --git-common-dir is immune, and it is also correct inside
 *     a linked worktree, where --git-dir points at .git/worktrees/<name> —
 *     which is not where hooks live.
 */
function renderPrevHookPath(hookName, prevRef) {
  if (prevRef.kind === "literal") return `"${prevRef.dir}/${hookName}"`;
  return `"$(git rev-parse --git-common-dir)/hooks/${hookName}"`;
}

/**
 * The block that runs the project's original hook first.
 *
 * POSIX sh only — no arrays, no [[ ]], no GNU-only mktemp flags: this runs in
 * Git Bash on Windows as well as macOS and Linux.
 *
 * `-x` is the right test, not `-f`: on POSIX git itself skips hooks that are not
 * executable, so running one anyway would fail with 126 and break a commit that
 * used to pass. On Windows everything reports executable, which matches what git
 * does there.
 *
 * Arguments are forwarded as ${1+"$@"} rather than plain "$@" because the hook
 * this gets prepended to runs under `set -u`, and bash 3.2 — still /bin/bash on
 * macOS — treats an unset "$@" as an unbound variable and aborts. pre-commit is
 * called with no arguments, so plain "$@" would break exactly there.
 */
function buildChainShim(hookName, prevRef, { duplicateStdin = false } = {}) {
  const prev = renderPrevHookPath(hookName, prevRef);
  const origin = prevRef.kind === "literal" ? `${prevRef.dir}/` : "git's own hooks directory";
  const head = `# >>> guardrails-kit: chained hook >>>
# This project already had a '${hookName}' hook in ${origin}. Installing the
# guardrails kit pointed core.hooksPath at .husky/, which makes git ignore that
# directory completely — so this block runs the original first and keeps its
# exit code. Delete the block to stop chaining; the uninstaller removes it too.
__gk_prev=${prev}`;
  const foot = "# <<< guardrails-kit: chained hook <<<";

  if (!duplicateStdin) {
    return `${head}
if [ -x "$__gk_prev" ]; then
  "$__gk_prev" \${1+"$@"} || exit $?
fi
${foot}
`;
  }

  return `${head}
if [ -x "$__gk_prev" ]; then
  # git feeds this hook on stdin, and both hooks need to see all of it.
  __gk_in="$(mktemp)"
  trap 'rm -f "$__gk_in"' EXIT
  cat > "$__gk_in"
  "$__gk_prev" \${1+"$@"} < "$__gk_in" || exit $?
  exec < "$__gk_in"
fi
${foot}
`;
}

/**
 * A complete hook for the types the kit does not generate. Without these, a
 * project's commit-msg / post-merge / pre-rebase / … simply stop running, with
 * nothing to replace them.
 *
 * If the original is missing on someone else's machine, this exits 0 and does
 * nothing — which is why it can be committed safely.
 */
function buildPassthroughHook(hookName, prevRef) {
  return `#!/usr/bin/env sh
# Generated by ai-agents-guardrails-kit. This file exists ONLY to keep your own
# '${hookName}' hook running: the kit sets core.hooksPath to .husky/, and git then
# ignores every other hooks directory. The kit adds no checks of its own here.

${buildChainShim(hookName, prevRef)}`;
}

/** Insert a shim right after the shebang + `set` line, never before them. */
function prependShim(hookText, shim) {
  if (!shim) return hookText;
  const lines = hookText.split("\n");
  // Keep the shebang first, then any leading comments and the `set -euo` line,
  // so the shim inherits the same shell options the rest of the hook runs under.
  let at = 1;
  while (at < lines.length && (lines[at].startsWith("#") || lines[at].startsWith("set ") || lines[at] === "")) {
    at++;
  }
  return [...lines.slice(0, at), "", shim.trimEnd(), "", ...lines.slice(at)].join("\n");
}

module.exports = {
  buildPolicyYaml,
  buildPreCommit,
  buildPrePush,
  buildCiWorkflow,
  buildGitlabCiYaml,
  buildChainShim,
  buildPassthroughHook,
  prependShim,
  renderPrevHookPath,
  HOOKS_WITH_STDIN,
  CORE_BLOCKED_COMMANDS,
  CORE_PROTECTED_PATHS,
};
