/**
 * generate.js — renders policy.yaml, .husky/pre-commit, .husky/pre-push,
 * and .github/workflows/security.yml from the CORE (language-agnostic)
 * rules plus the extra rules contributed by each selected stack profile.
 */
const { STACKS } = require("./stacks");

// Core rules apply regardless of language — they operate on shell/git/db
// semantics, not on the project's source language.
const CORE_PROTECTED_PATHS = [
  ".env", ".env.*", "**/*credentials*", "**/*secret*",
  "~/.ssh/**", "~/.aws/**", "~/.config/gcloud/**", "**/*.pem", "**/*.key",
];

const CORE_BLOCKED_COMMANDS = [
  { pattern: "\\bgit\\s+push\\s+(--force|-f|--force-with-lease)\\b", action: "deny", reason: "Force push blocked." },
  { pattern: "\\bgit\\s+push\\b", action: "ask", reason: "Pushing changes requires explicit human approval." },
  { pattern: "\\bgit\\s+(reset\\s+--hard|clean\\s+-f|branch\\s+-D)\\b", action: "deny", reason: "Destructive Git operation blocked." },
  { pattern: "\\brm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*|--recursive.*--force|--force.*--recursive)\\b", action: "deny", reason: "Recursive forced deletion blocked." },
  { pattern: "\\b(git\\s+commit\\s+.*--no-verify|git\\s+push\\s+.*--no-verify)\\b", action: "deny", reason: "Hook bypass is not permitted." },
  { pattern: "\\b(DROP\\s+DATABASE|DROP\\s+TABLE|TRUNCATE)\\b", action: "deny", reason: "Destructive database operation blocked." },
  { pattern: "\\bDELETE\\s+FROM\\b(?!.*\\bWHERE\\b)", action: "deny", reason: "DELETE without WHERE clause blocked." },
  { pattern: "\\bDELETE\\s+FROM\\b", action: "ask", reason: "Potentially destructive database operation requires approval." },
  { pattern: "\\bcurl\\b.*\\|\\s*(sh|bash|zsh)\\b", action: "deny", reason: "curl-pipe-shell execution blocked." },
  { pattern: "\\bdocker\\s+push\\b", action: "ask", reason: "Pushing a container image requires approval." },
  { pattern: "\\b(aws|gcloud|az)\\s+.*(delete|terminate|destroy)\\b", action: "ask", reason: "Cloud-provider destructive action requires approval." },
];

function yamlStr(s) {
  return JSON.stringify(s); // valid YAML flow scalar, handles escaping
}

function renderBlockedCommand(rule) {
  return `  - pattern: '${rule.pattern.replace(/'/g, "''")}'\n    action: ${rule.action}\n    reason: ${yamlStr(rule.reason)}\n`;
}

function renderCheck(check) {
  return `  - name: ${check.name}\n    command: ${yamlStr(check.command)}\n`;
}

function buildPolicyYaml(selectedStackKeys) {
  const stacks = selectedStackKeys.map((k) => STACKS[k]).filter(Boolean);

  const blockedCommands = [...CORE_BLOCKED_COMMANDS];
  stacks.forEach((s) => blockedCommands.push(...(s.extraBlocked || [])));

  const checks = [];
  stacks.forEach((s) => {
    s.checks.forEach((c) => {
      if (!checks.find((existing) => existing.name === c.name && existing.command === c.command)) {
        checks.push(c);
      }
    });
  });

  const allExtensions = [...new Set(stacks.flatMap((s) => s.changedExtensions))];
  const checkNames = checks.map((c) => c.name);

  let out = "version: 1\n\n";
  out += `# Stacks detected/selected at install time: ${stacks.map((s) => s.label).join(", ") || "(none — generic project)"}\n`;
  out += "# This file is generated by install.js. Edit freely — re-running the\n";
  out += "# installer will NOT overwrite it if it already exists (writes .new instead).\n\n";

  out += "protected_paths:\n" + CORE_PROTECTED_PATHS.map((p) => `  - "${p}"\n`).join("");
  out += "\nblocked_commands:\n" + blockedCommands.map(renderBlockedCommand).join("\n");

  out += "\nsensitive_tools:\n  - write_file\n  - edit_file\n  - run_command\n  - browser\n  - network_request\n";
  out += "\napproval_required:\n  - production\n  - deployment\n  - database_migration\n  - secret_rotation\n  - git_push\n";

  out += "\nrequired_checks:\n";
  out += checks.length
    ? checks.map(renderCheck).join("")
    : "  # No stack detected — add your test/lint/typecheck commands here manually.\n";

  out += "\ncompletion_rules:\n";
  if (allExtensions.length) {
    out += `  - changed_extensions: [${allExtensions.map((e) => `"${e}"`).join(", ")}]\n    require: [${checkNames.join(", ")}]\n`;
  }
  out += `  - changed_files:\n      - "Dockerfile"\n      - ".github/workflows/**"\n    require: []\n`;

  return out;
}

function renderShellChecks(stacks, indent = "") {
  const lines = [];
  stacks.forEach((s) => {
    s.checks.forEach((c) => {
      lines.push(`${indent}echo "[${c.name}] ${s.label}"`);
      lines.push(`${indent}${c.command}`);
    });
  });
  return lines.length ? lines.join("\n") : `${indent}echo "No stack-specific checks configured — edit .husky/pre-push manually."`;
}

function buildPreCommit(selectedStackKeys) {
  return `#!/usr/bin/env bash
# Fast local checks. Assume this CAN be bypassed with --no-verify — it's a
# convenience layer, not the enforcement layer (that's CI + branch protection).
set -euo pipefail

echo "[pre-commit] Checking for secrets..."
if command -v gitleaks >/dev/null 2>&1; then
  gitleaks protect --staged --redact
else
  echo "[pre-commit] gitleaks not installed, skipping secret scan (install: https://github.com/gitleaks/gitleaks)"
fi

echo "[pre-commit] Done."
`;
}

function buildPrePush(selectedStackKeys) {
  const stacks = selectedStackKeys.map((k) => STACKS[k]).filter(Boolean);
  return `#!/usr/bin/env bash
# Slower checks: full test suite per detected stack, then the completion gate.
set -euo pipefail

${renderShellChecks(stacks)}

echo "[pre-push] Completion gate..."
python3 .agent-security/final_check.py
`;
}

function buildCiWorkflow(selectedStackKeys) {
  const stacks = selectedStackKeys.map((k) => STACKS[k]).filter(Boolean);
  const setupSteps = stacks
    .map(
      (s) => `      - uses: ${s.ci.setupAction}
        with:
          ${s.ci.withBlock}
      - name: Install deps (${s.label})
        run: ${s.ci.install}`
    )
    .join("\n\n");

  const checkSteps = stacks
    .flatMap((s) => s.checks.map((c) => `      - name: ${c.name} (${s.label})\n        run: ${c.command}`))
    .join("\n\n");

  return `# Place at .github/workflows/security.yml
name: security-gate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  guardrails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install policy engine deps
        run: pip install pyyaml pytest --break-system-packages

      - name: Test policy engine
        run: pytest .agent-security/test_policy_engine.py

${setupSteps || "      # No stack detected at install time — add your language's setup step here."}

${checkSteps || "      # No stack-specific checks configured."}

      - name: Secret scan
        uses: gitleaks/gitleaks-action@v2

      # Add SAST / dependency scanning here (Semgrep, npm audit, composer audit, etc).
`;
}

module.exports = { buildPolicyYaml, buildPreCommit, buildPrePush, buildCiWorkflow };
